version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=adminConfig
      - POSTGRES_PASSWORD=adminConfig
    ports:
      - '5435:5435'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local